@host = localhost:8080
@id = 3
DELETE  http://{{host}}/user/admin/photo/{{id}} HTTP/1.1
content-type: application/json
authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MiwidXNlcm5hbWUiOiJqb2huLndpbGxpYW1zIiwiZW1haWwiOiJqb2huLndpbGxpYW1zQGdtYWlsLmNvbSIsImV4cCI6MTY5MzM2NTMxOH0.dYsUnLdbnX3zRbnvrKGQHro1zInkIxaPurEoFxS4KtY
