@host = localhost:8080
@id = 4
PUT http://{{host}}/user/admin/photo/{{id}} HTTP/1.1
content-type: application/json
authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MywidXNlcm5hbWUiOiJhYmR1bGhhbGltIiwiZW1haWwiOiJhYmR1bGhhbGltQGdtYWlsLmNvbSIsImV4cCI6MTY5MzQxODQ1NX0.EQ-hA6RFrwUozZY_AKRR7Az692viJ8AC6Zs1faKMrIE

{
    "title": "This is photo",
    "caption": "this is new photo",
    "photoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/RedCat_8727.jpg/1200px-RedCat_8727.jpg"
}